language: python
python:
  - "2.7"
  - "3.4"
before_install:
  - sudo add-apt-repository -y ppa:ubuntugis/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -y libgdal1h gdal-bin libgdal-dev
install:
  - pip install --install-option="--no-cython-compile" cython==0.21.2
  - "pip install -r requirements-dev.txt"
  - "pip install git+https://github.com/mapbox/rasterio.git#egg=rasterio"
  - "pip install -e .[test]"
script: 
  - py.test
